Revert "Docs navigation update (#297)"
This reverts commit 445ee245ae19539a53f4df902f1b6f6f228fc047.

The change in #297 introduces logic in `docusaurus.config.ts` that
always assumes the sidebar config is in the same location, regardless of
version configuration. However, the `Lint (Docs)` job in
`gravitational/teleport`, builds the docs with a single configured
version[1]. This means that the job always fails with an error message
resmebling the following, because the sidebar in the single-version
scenario would be in `sidebars.json`, not the path expected by
`docusaurus.config.ts`.

```text
Error:  Error: Docusaurus could not load module at path "/home/runner/work/teleport/teleport/docs/docusaurus.config.ts"
Cause: Cannot find module './versioned_sidebars/version-current-sidebars.json'
Require stack:
- /home/runner/work/teleport/teleport/docs/docusaurus.config.ts
    at loadFreshModule (/home/runner/work/teleport/teleport/docs/node_modules/@docusaurus/utils/lib/moduleUtils.js:36:15)
    at loadSiteConfig (/home/runner/work/teleport/teleport/docs/node_modules/@docusaurus/core/lib/server/config.js:36:62)
    ... 6 lines matching cause stack trace ...
    at async file:///home/runner/work/teleport/teleport/docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Cannot find module './versioned_sidebars/version-current-sidebars.json'
```

[1]: https://github.com/gravitational/teleport/blob/07e85c50af7819ec3a046cdcfca1c8f59f59a6f5/.github/workflows/doc-tests.yaml#L124